name: Hello World

on: 
  [push]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! by ryde."
      - run: echo "Hello World! by ryde. one more."
      - run: cat /etc/os-release