name: Hello World

on: 
  push:
    branches: [ main ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! by ryde."
      - run: cat /etc/os-release
      # - uses: actions/checkout@v1
      # - run: cat sample.txt
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          check-latest: true
      - run: python -m venv venv
      - run: source ./venv/bin/activate
      - run: pip install -U pip
      - run: pip install -U setuptools
      - run: pip install sphinx pytest
      - run: python --version